### ISSUE TITLE
Building on java 9 raises an exception

### ISSUE THREAD

**Issue by dvallin** [Transmode/gradle-docker#129]
In our gradle file we have (among lots of other things)

```
task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'se.transmode.gradle:gradle-docker:1.2'
    }
}

targetCompatibility = 9

docker {
    baseImage "openjdk:9-jre"
}

task buildDocker(type: Docker, dependsOn: build) {
    version = versionDetails().gitHash
    applicationName = rootProject.name.toLowerCase()
    entryPoint(['java', '-jar', "${jar.archiveName}"])
    addFile {
        from jar
    }
}
```

running `./gradlew buildDocker` gives an error message

```
Execution failed for task ':service:buildDocker'.
> No Java base image for the supplied target 1.9 found.
```

This would be the expected behavior for not configuring a baseImage. But if we set the targetCompatibility to 1.8 the image builds fine with:

```
Step 1/3 : FROM openjdk:9-jre
 ---> 684d13528523
Step 2/3 : ENTRYPOINT java -jar service-6b91d17906.jar
 ---> Using cache
 ---> 1474d66a7574
Step 3/3 : ADD add_2.tar /
 ---> 9c2a11d2f78b
Successfully built 9c2a11d2f78b
```

So the baseImage is picked up after all!

See pull request https://github.com/Transmode/gradle-docker/pull/128

**Comment by dvallin** [comment]
We decided to include a Dockerfile instead of using the DSL

```
task buildDocker(type: Docker) {
    dockerfile = 'Dockerfile'
    version = versionDetails().gitHash
    applicationName = rootProject.name.toLowerCase()
    entryPoint(['java', '-jar', "${jar.archiveName}"])
    addFile {
        from jar
    }
}
```

with a Dockerfile as simple as

`FROM openjdk:9-jre`

now it works with even with `targetCompatibility = 9`

**Comment by NaikSoftware** [comment]
Same error with any JDK > 8

**Comment by benparvar** [comment]
> We decided to include a Dockerfile instead of using the DSL
> 
> ```
> task buildDocker(type: Docker) {
>     dockerfile = 'Dockerfile'
>     version = versionDetails().gitHash
>     applicationName = rootProject.name.toLowerCase()
>     entryPoint(['java', '-jar', "${jar.archiveName}"])
>     addFile {
>         from jar
>     }
> }
> ```
> 
> with a Dockerfile as simple as
> 
> `FROM openjdk:9-jre`
> 
> now it works with even with `targetCompatibility = 9`

This works fine!!!! 

Thanks
