### ISSUE TITLE
Use the installation directory as the default working directory

### ISSUE THREAD

**Issue by EronWright** [Transmode/gradle-docker#134]
For the `distDocker` task that is generated in the presence of the application plugin, consider setting the `workingDir` to the installation directory.   This would allow applications to use relative paths when referring to the conf directory, etc.

Here's a workaround, manually configure the `distDocker` task in `build.gradle`:
```groovy
distDocker {
  def installDir = "/" + project.distTar.archiveName - ".${project.distTar.extension}"
  workingDir installDir
}
```

**Comment by bjornmagnusson** [comment]
That´s an interesting idea. We highly welcome all contributions, if you issue an PR for we may take a look at it
