### ISSUE TITLE
Cannot find switchUser in DockerTask

### ISSUE THREAD

**Issue by kbyyd24** [Transmode/gradle-docker#136]
I found that I can use `switchUser(String usernameOrId)` method in `DockerTask` in readme.
But I cannot find the method in the class.

How can I use it?

My gradle is this:

```groovy
task stubDocker(type: Docker, dependsOn: build) {
    switchUser('root')
    addFile(file("${buildDir}/libs/${rootProject.name}-${version}.jar"), "/root/stub-runner.jar")
    exposePort(9999)
    defaultCommand(["java", "-jar", "~/stub-runner.jar"])
}
```

**Comment by bjornmagnusson** [comment]
Unfortunately this functionality is not available in any released version, only in the master.
You may try it out by publishing the project jar to maven local, using the task **publishToMavenLocal**. This will publish **gradle-docker** artifact into your local maven repo with the version **1.3-SNAPSHOT**
