### ISSUE TITLE
Exposing UDP port

### ISSUE THREAD

**Issue by Nashati** [Transmode/gradle-docker#142]
Hi,
does the plugin support exposing UDP ports? 
I see just 'void exposePort(Integer port)'.

Thanks.

**Comment by bjornmagnusson** [comment]
Yes, in master branch (not released in any published version).
Then one can use `void exposePort(String port)` to expose udp ports.

**Comment by Nashati** [comment]
Thanks.
So do you have any plans for publishing a new version?. 
if not, how can I use master version in my project?

**Comment by bjornmagnusson** [comment]
There are plans, but no specifics yet. For local development you can publish the master version into your local m2 repository using the gradle task publishToMavenLocal, and then reference 1.3-SNAPSHOT as version in your project. 
Aware of the issues with this...
