### ISSUE TITLE
is this plugin not in the official gradle plugin repo?

### ISSUE THREAD

**Issue by logemann** [Transmode/gradle-docker#146]
I would like to use the

plugins {
}

syntax in the gradle build file.

**Comment by lemix-cg** [comment]
Workaround:
`**settings.gradle**:`
`pluginManagement {
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case 'gradle-docker':
                    useModule 'se.transmode.gradle:gradle-docker:1.2'
                    break
            }
        }
    }
    repositories {
        gradlePluginPortal()
        mavenCentral()
        jcenter()
    }
}`

**Comment by bjornmagnusson** [comment]
@lemix-cg That´s great input. 
Would you mind open a PR to add this workaround to the README?
