### ISSUE TITLE
Can you also add base images for openjdk 10 and openjdk 11

### ISSUE THREAD

**Issue by wavermartijn** [Transmode/gradle-docker#148]
https://github.com/Transmode/gradle-docker/blob/3d22f0904058a3530ff3eda31ea54f78377ec01e/src/main/java/se/transmode/gradle/plugins/docker/JavaBaseImage.java#L27

**Comment by wavermartijn** [comment]
Sorry, I saw you have a commit for the most recent versions already. Hope they will be merged soon

**Comment by jomach** [comment]
shouldn't this work: 
docker {
    baseImage = 'openjdk:11-jre-slim'
 ...
}

It fails on my because of 
Caused by: java.lang.IllegalArgumentException: No Java base image for the supplied target 11 found.

**Comment by bjornmagnusson** [comment]
Fixed by #145
