### ISSUE TITLE
dial unix /var/run/docker.sock: permission denied

### ISSUE THREAD

**Issue by cojennin** [Transmode/gradle-docker#28]
Bit new to gradle and docker, so not sure if this is a legitimate issue, but I'm encountering the issue mentioned in the title when trying to run a task that builds a Docker image from an external dockerfile.

Currently on Ubuntu 14.04. Not sure if there's a way to run this task with elevated permissions or run docker without, just wanted to see if anyone might have a suggestion.

**Comment by dtanzer** [comment]
Even though this issue is already closed, here is a nicer option to solve it - It does not require you to add yourself to the docker group. Just configure docker in your gradle build script like this:

docker {
	dockerBinary = "sudo docker"
}
