### ISSUE TITLE
Automatically build and run images

### ISSUE THREAD

**Issue by the-wastl** [Transmode/gradle-docker#40]
Am I right that it is not possible to build and run images automatically, or am I just missing something?

BR,
wastl

**Comment by sfitts** [comment]
I actually have changes to support execution of images which I need to merge into dev.  I'll try to get to that this week.

**Comment by sfitts** [comment]
There is a version of the run task in dev now, but it does have a few issues I have fixes for (turns out I was farther ahead on my merging that I thought ;) ).  As for merging dev and producing a release -- that's outside my purview.

**Comment by the-wastl** [comment]
thank you very much
