### ISSUE TITLE
define username and password for repository

### ISSUE THREAD

**Issue by inkrement** [Transmode/gradle-docker#46]
is it possible to define the username and password for docker hub?

**Comment by mattgruter** [comment]
Yes, use the ```apiUser``` and ```apiPassword``` properties:

See https://github.com/Transmode/gradle-docker#docker-remote-api

**Comment by SreekarVanguru** [comment]
Matt - just checking aren't apiUser and apiPassword used to authenticate user with Docker server to run docker commands ?. Which properties do we need to use to authenticate when pushing the image to private registry/repository ?
