### ISSUE TITLE
Exposing UDP ports

### ISSUE THREAD

**Issue by mattgruter** [Transmode/gradle-docker#48]
Exposing UDP ports on the command line or Dockerfile uses the syntax 162/udp
The ```exposePort(port)``` method expects a port to be an integer.

Thus

    exposePort("162/udp")

doesn't work

**Comment by bjornmagnusson** [comment]
Fixed with 8e9d9e4

**Comment by benoahriz** [comment]
> Could not find method exposePort() for arguments [162/udp] on task ':doDocker' of type se.transmode.gradle.plugins.docker.DockerTask.

this isnt working.

**Comment by benoahriz** [comment]
just built this locally and seems to work...
