### ISSUE TITLE
There is a bug in NativeDockerClient.executeAndWait()

### ISSUE THREAD

**Issue by jt214** [Transmode/gradle-docker#59]
The NativeDockerClient.executeAndWait() method is not handling the output buffer properly.

See: http://stackoverflow.com/questions/159148/groovy-executing-shell-commands

When the files including in the container are large (approx. 750mb), the executeAndWait method just hangs indefinitely.

The method should be written like:

    private static String executeAndWait(String cmdLine) {
        print "\nexecuteAndWait(${cmdLine})\n\n"

        def process = cmdLine.execute()
        def inStream = new StringBuffer()
        def outStream = new StringBuffer()

        process.waitForProcessOutput(inStream, outStream)
        if (process.exitValue()) {
            throw new GradleException("Docker execution failed\nCommand line [${cmdLine}] returned:\n${outStream}")
        }
        return inStream
    }

**Comment by bjornmagnusson** [comment]
This is fixed in dev branch already
