### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by gmessner** [Transmode/gradle-docker#78]
Not really an issue, just a request for info.  I'm about to embark on a new project and would like to use this plug-in but version 1.3. 

Any idea on when 1.3 might be officially released?

**Comment by bjornmagnusson** [comment]
Currently looking into some final fixes to include, release of 1.3 coming soon

**Comment by gmessner** [comment]
Great, thanks for the update.

I'll go ahead and close this issue and will keep an eye on the project to use in future endeavors.
