### ISSUE TITLE
push / tag

### ISSUE THREAD

**Issue by redr0bin** [Transmode/gradle-docker#84]
Hi,
trying to build and push docker image using this gradle plugin.

task buildImage(type: Docker) {
    baseImage = 'hub.test.com/test-base:latest'
    registry = 'hub.test.com'
    tag = 'test-image:test'
    push = false

    if (project.hasProperty('pushImage')) {
        push = true
    }
   // just exec some script for example
    runCommand("./post_install.sh")
}

When I do buildImage image is being built, but when task tries to push the resulting image it encounters error "unauthorized: authentication required". My registry is insecure via http, docker daemon is configured for it. What can be the problem here ?

**Comment by redr0bin** [comment]
Sorry, everything work like a charm with pushing, some weird docker daemon behaviour. After docker daemon restart image is being pushed.

**Comment by frvi** [comment]
Nice to hear that it worked out. 👍
