### ISSUE TITLE
Unable to get gradle build working with an external Dockerfile

### ISSUE THREAD

**Issue by alan-czajkowski** [Transmode/gradle-docker#88]
@mattgruter can you please post a complete example using an external Dockerfile, the documentation is not clear enough

I tried:

```
docker {
  dockerfile "./Dockerfile"
}
```

and I get the error:

```
Could not find method dockerfile() for arguments [./Dockerfile] on root project 'bibliocommons'.
```

**Comment by sanimalp** [comment]
I think you just have a minor syntax error. 

`  dockerfile = file('Dockerfile')` 

should work.

**Comment by bjornmagnusson** [comment]
Just tried (with plugin version 1.2 and the native client). 

dockerfile = './Dockerfile' works
dockerfile = 'Dockerfile' works
dockerfile "./Dockerfile" works

Can not reproduce this error.
